server:
  port: 8100
  shutdown: graceful

logging:
  level:
    root: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB.URI:localhost}
    username: ${DB.USERNAME:root}
    password: ${DB.PASSWORD:123456}
