server:
  port: 8000
  shutdown: graceful

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8100/oauth2/jwks
  cloud:
    gateway:
      routes:
       - id: auth-service
         uri: http://localhost:8100
         predicates:
           - Path=/auth

logging:
  level:
    root: INFO
#    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics
