server:
  port: 8000
  shutdown: graceful

logging:
  level:
    root: INFO
#    org.springframework.boot.autoconfigure: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics
